dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.2
  file_picker: ^8.0.3
  in_app_purchase: ^3.2.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  
  # المحرك العالمي الحقيقي لمعالجة وقص وتصدير الفيديوهات بالفلاتر
  ffmpeg_kit_flutter: ^6.0.3
  
  # حزمة الأيقونات الحديثة لتصميم واجهة مشابهة لـ CapCut
  cupertino_icons: ^1.0.6
