dependencies:
  flutter:
    sdk: flutter

  # مكتبة اختيار الصور والفيديوهات من المعرض
  image_picker: ^1.1.2 
  
  # مكتبة اختيار ملفات متعددة ومتقدمة من الجهاز (بديل قوي)
  file_picker: ^8.0.3

  # مكتبة إدارة الاشتراكات والمشتريات داخل التطبيق
  in_app_purchase: ^3.2.0
  
