name: Auto Create Android and Build APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'

    - name: Inject Missing Android Folder
      run: |
        flutter create --project-name=ymai_project --platforms=android .
        
    - name: Fix Android SDK Versions
      run: |
        sed -i 's/minSdkVersion.*/minSdkVersion 24/g' android/app/build.gradle
        sed -i 's/targetSdkVersion.*/targetSdkVersion 34/g' android/app/build.gradle

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release
